# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
    - MYSQL_ROOT_PASSWORD=123456
    - MYSQL_DATABASE=base
    volumes:
    - ./data:/var/lib/mysql
    - ./init:/docker-entrypoint-initdb.d
    ports:
    - 3306:3306
  adminer:
    image: adminer
    restart: always
    ports:
    - 8080:8080















#version: '3'
#services:
#    db:
#        image: "mysql:5.7.18"
#        ports:
#            - "${DB_PORT:-3306}:3306"
#        environment:
#            - MYSQL_ROOT_PASSWORD=123456
#            - MYSQL_DATABASE=dev
#            - MYSQL_USER=dev
#            - MYSQL_PASSWORD=dev
#        volumes:
#          - ./data:/var/lib/mysql
#        command: ['--character-set-server=utf8mb4','--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
#
#
#    init_db:
#        build: ./init/
#        volumes:
#            - ./init/sql:/mnt/sql
#        depends_on:
#            - db
#