version: '3'
services:
    db:
        image: "mysql:5.7.18"
        ports:
            - "${DB_PORT:-3306}:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=1234567
            - MYSQL_DATABASE=dev
            - MYSQL_USER=dev
            - MYSQL_PASSWORD=dev
        command: ['--character-set-server=utf8mb4','--collation-server=utf8mb4_unicode_ci']


    init_db:
        build: ./init/
        volumes:
            - ./init/sql:/mnt/sql
        depends_on:
            - db
    